name: gongyusong' blog
description: Blogging about stuffs
meta_description: "this is gongyusong's blog, blogging about stuffs"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'gongyusong.com'
author:         'gongyusong'
